# **Import Libraries**

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

# **Data**

In [5]:
df = pd.read_csv('payment_fraud.csv')
df.head()

accountAgeDays  numItems  ...  paymentMethodAgeDays label
0              29         1  ...             28.204861     0
1             725         1  ...              0.000000     0
2             845         1  ...              0.000000     0
3             503         1  ...              0.000000     0
4            2000         1  ...              0.000000     0

[5 rows x 6 columns]

In [14]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [33]:
print(x)

[[0.0 1.0 0.0 ... 1 4.7454019999999995 28.2048611111]
 [0.0 0.0 1.0 ... 1 4.742303 0.0]
 [1.0 0.0 0.0 ... 1 4.921318 0.0]
 ...
 [1.0 0.0 0.0 ... 1 4.742303 0.0]
 [1.0 0.0 0.0 ... 1 4.921318 236.082638889]
 [0.0 1.0 0.0 ... 1 5.040929 0.0006944444444439998]]


In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [34]:
print(x)

[[0.0 1.0 0.0 ... 1 4.7454019999999995 28.2048611111]
 [0.0 0.0 1.0 ... 1 4.742303 0.0]
 [1.0 0.0 0.0 ... 1 4.921318 0.0]
 ...
 [1.0 0.0 0.0 ... 1 4.742303 0.0]
 [1.0 0.0 0.0 ... 1 4.921318 236.082638889]
 [0.0 1.0 0.0 ... 1 5.040929 0.0006944444444439998]]


In [22]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=42)

# **Training model**

In [23]:
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(accuracy_score(y_pred,y_test))

1.0


In [24]:
print(confusion_matrix(y_test,y_pred))

[[12753     0]
 [    0   190]]
